config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'
  root 'home#index'
  resources :memes
  resources :users, :only =>[:show]
  match '/users/:id',     to: 'users#show',       via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meme
end

app/models/meme.rb
class Meme < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    has_one_attached :picture

    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memes, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to meme_path(@comment.meme_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to meme_path(@comment.meme_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :meme_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery with: :exception
  def index
    @memes = Meme.all
  end

  def show
    @meme = Meme.find(params[:user_id])
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    def show
      @meme = Meme.find(params[:id])
      @comments = @meme.comments.all
      @comment = @meme.comments.build
    end

    def new
      @meme = Meme.new
    end

    def create
      @meme = current_user.memes.create(meme_params)

      if @meme.save
        flash[:notice] = "Meme successfully created"
        redirect_to root_path
      else
        flash[:alert] = "Something bad happened"
        redirect_to new_meme_path
      end
    end

    def edit
      @meme = Meme.find(params[:id])
    end

    def update
      @meme = Meme.find(params[:id])

      if @meme.save
        flash[:notice] = "Meme successfully created"
        redirect_to root_path
      else
        flash[:alert] = "Something bad happened"
        redirect_to new_meme_path
      end
    end

    def destroy
      @meme = Meme.find(params[:id])
      if @meme.destroy
        flash[:notice] = "Meme successfully destroyed"
        redirect_to root_path
      else
        flash[:alert] = "Something bad happend in destroying meme"
        redirect_to root_path
      end
    end

    private
    def meme_params
      params.require(:meme).permit(:title, :body, :meme_type, :picture)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except => [:show]

  def show
    @user = User.find_by_name(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.hidden_field :meme_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<% if current_user.id == @meme.user_id %>
    <%= render 'form', comment: @comment %>
<% else %>
    <p>You are not allowed to be here</p>
<% end %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Seller name</th>
      <th>Body</th>
      <th>Clothes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.meme_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <% if current_user.name == comment.user_name %>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seller name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Clothes:</strong>
  <%= @comment.meme_id %>
</p>
<% if current_user.name == @comment.user_name %>
  <%= link_to 'Edit', edit_comment_path(@comment) %> |
<% end %>
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<h1>Listing clothes</h1>

<table style="width:100%">
  <tr style="padding:15px">
    <th>Avatar</th>
    <th>Seller</th>
    <th>Title</th>
    <th>Text</th>
    <th>Picture</th>
  </tr>

  <% @memes.each do |meme| %>
    <tr style="padding: 15px">
      <td><%= image_tag(meme.user.avatar.variant(resize: "50x50")) if meme.user.avatar.attached? %></td>
      <td><%= link_to meme.user.name, user_path(meme.user.name)%></td>
      <td><%= meme.title %></td>
      <td><%= meme.body %></td>
      <td><%= image_tag(meme.picture.variant(resize: "250x250")) if meme.picture.attached? %></td>
      <td><%= link_to 'Show', meme_path(meme) %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clothes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= link_to 'Магазин', root_path %>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
        Logged in as <strong><%= current_user.name %></strong>.
        <%= link_to 'New clothing', new_meme_path %>
        <%= link_to 'Profile', user_path(current_user.name)%>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    <%= yield %>
    </p>
  </body>
</html>

app/views/memes/edit.html.erb
<h1>Edit product</h1>
<% if current_user.id == @meme.user_id %>
    <%= form_with model: @meme, local: true do |form| %>
      <% if @meme.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@meme.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @meme.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# if flash[:notice] %>
      <!--    <div class="notice"><%#= flash[:notice] %></div>-->
      <%# end %>

      <%# if flash[:alert] %>
      <!--    <div class="alert"><%#= flash[:alert] %></div>-->
      <%# end %>

      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>

      <p>
        <%= form.label :text %><br>
        <%= form.text_area :body %>
      </p>

      <div class="field">
        <%= form.label :picture %>
        <%= form.file_field :picture %>
      </div>

      <p>
        <%= form.submit %>
      </p>
    <% end %>
<% else %>
    <p>You are not allowed to be here</p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/memes/new.html.erb
<h1>New product</h1>
<%= form_with model: @meme, local: true do |form| %>
  <% if @meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meme.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @meme.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# if flash[:notice] %>
<!--    <div class="notice"><%#= flash[:notice] %></div>-->
  <%# end %>

  <%# if flash[:alert] %>
<!--    <div class="alert"><%#= flash[:alert] %></div>-->
  <%# end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :body %>
  </p>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/memes/show.html.erb
<p>
  <strong>Seller:</strong>
  <%= @meme.user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @meme.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @meme.body %>
</p>

<%= image_tag(@meme.picture, width: 200) if @meme.picture.attached? %> <br>

<% if current_user.name == @meme.user.name %>
  <%= link_to 'Edit', edit_meme_path(@meme) %> |
  <td><%= link_to 'Destroy', meme_path(@meme),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td> |
<% end %>
<%= link_to 'Back', root_path %>
<h3>Comments</h3>
<% if user_signed_in? %>
  <%= render partial: 'comments/form', locals: { comment: @comment } %>
<% end %>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br>
    <p><%= comment.body %></p>
    <% if comment.user_name == current_user.name %>
      <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<% if @user.name == current_user.name %>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<h2>Products of this user:</h2>
<table style="width:100%">
  <tr style="padding:15px">
    <th>Avatar</th>
    <th>Seller</th>
    <th>Title</th>
    <th>Text</th>
    <th>Picture</th>
  </tr>

  <% @user.memes.each do |meme| %>
    <tr style="padding: 15px">
      <td><%= image_tag(meme.user.avatar.variant(resize: "50x50")) if meme.user.avatar.attached? %></td>
      <td><%= link_to meme.user.name, user_path(meme.user.name)%></td>
      <td><%= meme.title %></td>
      <td><%= meme.body %></td>
      <td><%= image_tag(meme.picture.variant(resize: "250x250")) if meme.picture.attached? %></td>
      <td><%= link_to 'Show', meme_path(meme) %></td>
    </tr>
  <% end %>
</table>